name: 'comment-hider'
description: 'Github Action to hide Bot comments'
branding:
  color: gray-dark
  icon: check
author: 'kanga333'
inputs:
  github_token:
    description: 'The GitHub token used to create an authenticated client'
    required: true
  hide_user_name:
    description: 'GitHub username to hide comments'
    default: 'github-actions[bot]'
    required: false
  hide_reason:
    description: 'A value from https://docs.github.com/en/graphql/reference/enums#reportedcontentclassifiers'
    default: 'OUTDATED'
    required: false
  leave_visible:
    description: 'The number of most recent comments to leave untouched'
    default: '0'
    required: false
  issue_number:
    description: 'Issue number, needed when running with workflow_run trigger'
    default: ''
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
